## Numpy Array operation

In [1]:
import numpy as np

## 1D Array Slicing

In [ ]:
arr = np.arange(1,20,2)

print(arr)
print("\nBasic Slicing: ",arr[2:8])
print("\nWith Step: ",arr[1:8:3])
print("\nNegative indexing: ",arr[-5])

[ 1  3  5  7  9 11 13 15 17 19]

Basic Slicing:  [ 5  7  9 11 13 15]

With Step:  [ 3  9 15]

Negative indexing:  11


## 2D Array Slicing

In [12]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

print("Specific element: ",arr[2][0])
print("Entire row: ",arr[0])
print("Entire colum: ",arr[:,1])

Specific element:  7
Entire row:  [1 2 3]
Entire colum:  [2 5 8]


## Sorting

In [ ]:
unsorted = np.array([3,1,4,1,5,9,2,6])
print("Sorted Array: ",np.sort(unsorted))

unsorted_2D_arr = np.array([[3,1],
                            [1,2],
                            [2,3]])
print("\nSorted 2D array by column: \n",np.sort(unsorted_2D_arr,axis=0))
print("\nSorted 2D array by row: \n",np.sort(unsorted_2D_arr,axis=1))

Sorted Array:  [1 1 2 3 4 5 6 9]

Sorted 2D array by column: 
 [[1 1]
 [2 2]
 [3 3]]

Sorted 2D array by row: 
 [[1 3]
 [1 2]
 [2 3]]


## Filter

In [21]:
number = np.arange(1,11)
even_number = number[number % 2 == 0]
print("Even Number: ",even_number)

Even Number:  [ 2  4  6  8 10]


## Filter with Mask

In [22]:
mask = number > 5
print("Number greater than 5: ",number[mask])

Number greater than 5:  [ 6  7  8  9 10]


## Fancy indexing vs np.where()

In [25]:
indices = [0,2,4]
print(number[indices])

where_result = np.where(number>5)
print(where_result)
print("NP Where: ",number[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP Where:  [ 6  7  8  9 10]


In [26]:
condition_array = np.where(number>5,"True","False")
print(condition_array)

['False' 'False' 'False' 'False' 'False' 'True' 'True' 'True' 'True'
 'True']


### Merge Array

In [28]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6]


## Array Compatibility

In [29]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

print("Compatibility shapes: ",a.shape == b.shape)

Compatibility shapes:  True


## Add new data Row and Col Wise

In [37]:
original = np.array([[1,2],[3,4]])

new_row = np.array([[5,6]])
with_new_row = np.vstack((original,new_row))

print("Original: \n",original)
print("\nWith_new_row: \n",with_new_row)

new_col = np.array([[7],[8]])
with_new_col = np.hstack((original,new_col))

print("\nWith_col_row: \n",with_new_col)

Original: 
 [[1 2]
 [3 4]]

With_new_row: 
 [[1 2]
 [3 4]
 [5 6]]

With_col_row: 
 [[1 2 7]
 [3 4 8]]


## Delete Data

In [38]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr,3)

print("Array after deletion: ",deleted)

Array after deletion:  [1 2 3 5]
