In [3]:
import numpy as np

### creating array from list

In [4]:
arr_1d = np.array([1,2,3,4,5])
print(arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


### List vs Numpy array

In [33]:
py_list = [1,2,3]
print("Python list mulltiplication: ",py_list*2)

np_array = np.array([1,2,3])
print("Numpy array mulltiplication: ",np_array*2)

import time

start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\nList operation time: ",time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\nNumpy operation time: ",time.time() - start)

Python list mulltiplication:  [1, 2, 3, 1, 2, 3]
Numpy array mulltiplication:  [2 4 6]

List operation time:  0.06379556655883789

Numpy operation time:  0.006667375564575195


### creating array from scratch

In [35]:
zeros = np.zeros((3,4))
print("zeros array: \n",zeros)

ones = np.ones((2,2))
print("\nones array: \n",ones)

full = np.full((2,2),8)
print("\nfull array: \n",full)

random = np.random.random((3,3))
print("\nrandom array: \n",random)

sequence = np.arange(0,11,2)
print("\nsequence array: \n",sequence)


zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

ones array: 
 [[1. 1.]
 [1. 1.]]

full array: 
 [[8 8]
 [8 8]]

random array: 
 [[0.45917879 0.08237403 0.70598003]
 [0.45681313 0.12489566 0.04526507]
 [0.02733217 0.59601482 0.14275816]]

sequence array: 
 [ 0  2  4  6  8 10]


### Vector, Matrix and Tensor

In [38]:
vector = np.array([1,2,3])
print("vector: \n",vector)

matrix = np.array([[1,2,3],[4,5,6]])
print("\nmatrix: \n",matrix)

tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("\ntensor: \n",tensor)

vector: 
 [1 2 3]

matrix: 
 [[1 2 3]
 [4 5 6]]

tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array properties

In [44]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

print("Shape: ",arr.shape)
print("Dimension: ",arr.ndim)
print("Size: ",arr.size)
print("DType: ",arr.dtype)

Shape:  (3, 3)
Dimension:  2
Size:  9
DType:  int64


### Array Reshaping

In [55]:
arr = np.arange(12)
print("Original array: ",arr)

reshaped = arr.reshape((3,4))
print("\nReshaped array: \n",reshaped)

# flatten() and ravel() are used to convert a multi-dimensional array into a 1D array

# flatten() does not affect the original array.Always returns a copy of the original array
flattend = reshaped.flatten()
print("\nFlattend array: ",flattend)

# ravel() may affect the original array
raveled = reshaped.ravel()
print("\nRaveled array: ",raveled)

transpose = reshaped.T
print("\nTransposed array: \n",transpose)

Original array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flattend array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Raveled array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Transposed array: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
